### NOT TODO list API
@url=http://localhost:8000/api/v1/taskLists

### Get method

GET {{url}}

### Post Method

POST  {{url}}
Content-Type: application/json

{   

   "task":"reading",
   "hr":15,
   "type": "entry"
}

### Patch Method

PATCH  {{url}}
Content-Type: application/json

{   "id":1,
    "type":"bad"
}


### Delete Method
DELETE {{url}}/1